const workoutService = require('../../services/workoutService');
const dietReadService = require('../../diet/dietReadService');
const dietInsightService = require('../../diet/dietInsightService');
const scheduleService = require('../../dietSchedule/scheduleService');
const { getActivitySummary } = require('../../services/activitySummaryService');
const { getGlucoseSummary } = require('../../services/glucoseService');
const deviceService = require('../../services/deviceService');
const { readTool, evidence } = require('./helpers');

const DATE = { type: 'string', description: 'YYYY-MM-DD' };

// ------------------------------------------------------------------- diet

const getDietSummary = readTool({
  name: 'get_diet_summary',
  description: 'Calories and nutrients per day for the last N days (1-90, default 7), grouped by meal, plus how many logged meals still need review.',
  properties: { days: { type: 'integer', minimum: 1, maximum: 90 } },
  async execute(args, { userId }) {
    return { data: await dietReadService.getSummary(userId, args.days), evidence: [] };
  },
});

const listFoodEntries = readTool({
  name: 'list_food_entries',
  description: 'Logged meals/foods with calories and nutrients. Defaults to today; pass `date`, or `from`/`to`, or `unconfirmed: true` for entries awaiting review.',
  properties: { date: DATE, from: DATE, to: DATE, unconfirmed: { type: 'boolean' } },
  async execute(args, { userId }) {
    const entries = await dietReadService.listEntries(userId, {
      date: args.date,
      from: args.from,
      to: args.to,
      unconfirmed: args.unconfirmed === true ? 'true' : undefined,
    });
    return { data: { entries }, evidence: evidence('food_entry', entries, 'id', 'name') };
  },
});

const getDietRecommendations = readTool({
  name: 'get_diet_recommendations',
  description:
    'Pattern analysis of recent eating with practical tips that take the person\'s confirmed lab results and active medicines into account. ' +
    'Generated by AI and cached; needs the person\'s "AI health insights" consent in EyeMyHealth.',
  properties: { days: { type: 'integer', minimum: 3, maximum: 90 } },
  async execute(args, { userId }) {
    const days = Math.min(Math.max(Number.parseInt(args.days, 10) || 14, 3), 90);
    const recommendation = await dietInsightService.getOrGenerateRecommendations(userId, { windowDays: days });
    return { data: { recommendation }, evidence: [] };
  },
});

const listDietSchedules = readTool({
  name: 'list_diet_schedules',
  description: 'Meal plans (diet schedules) the person has created or imported, newest first.',
  async execute(args, { userId }) {
    const schedules = await scheduleService.listSchedules(userId);
    return { data: { schedules }, evidence: evidence('diet_schedule', schedules, 'id', 'title') };
  },
});

const getDietSchedule = readTool({
  name: 'get_diet_schedule',
  description: 'One meal plan with every day\'s meals by id.',
  properties: { scheduleId: { type: 'string' } },
  required: ['scheduleId'],
  async execute(args, { userId }) {
    const schedule = await scheduleService.getScheduleWithEntries(userId, args.scheduleId);
    if (!schedule) return { data: { found: false }, evidence: [] };
    return { data: { found: true, schedule }, evidence: [{ type: 'diet_schedule', id: schedule.id, label: schedule.title }] };
  },
});

// --------------------------------------------------------------- workouts

const listWorkouts = readTool({
  name: 'list_workouts',
  description: 'Recent AI-coached workout sessions (newest first) with exercise, reps/duration and estimated calories.',
  properties: { limit: { type: 'integer', minimum: 1, maximum: 100 } },
  async execute(args, { userId }) {
    const workouts = await workoutService.history(userId, args.limit);
    return { data: { workouts }, evidence: evidence('workout', workouts) };
  },
});

const getWorkoutSummary = readTool({
  name: 'get_workout_summary',
  description: 'Detailed summary of one workout session by id: sets, reps, form feedback, fatigue and comparison with the previous session.',
  properties: { workoutId: { type: 'string' } },
  required: ['workoutId'],
  async execute(args, { userId }) {
    const data = await workoutService.getSummary(userId, args.workoutId);
    return { data, evidence: [{ type: 'workout', id: args.workoutId }] };
  },
});

const getWorkoutAnalytics = readTool({
  name: 'get_workout_analytics',
  description: 'Workout totals and trends across all completed sessions (frequency, volume, best efforts).',
  async execute(args, { userId }) {
    return { data: await workoutService.getAnalytics(userId), evidence: [] };
  },
});

const getExerciseProgression = readTool({
  name: 'get_exercise_progression',
  description: 'How performance on one exercise has changed over time. Get exercise ids from list_exercises.',
  properties: { exerciseId: { type: 'string' } },
  required: ['exerciseId'],
  async execute(args, { userId }) {
    return { data: await workoutService.getProgression(userId, args.exerciseId), evidence: [] };
  },
});

const listExercises = readTool({
  name: 'list_exercises',
  description: 'The exercises the AI workout coach can track, with their ids.',
  async execute() {
    return { data: { exercises: await workoutService.listExercises() }, evidence: [] };
  },
});

const listWorkoutPlans = readTool({
  name: 'list_workout_plans',
  description: "The person's saved workout plans.",
  async execute(args, { userId }) {
    const plans = await workoutService.listPlans(userId);
    return { data: { plans }, evidence: evidence('workout_plan', plans, 'id', 'name') };
  },
});

const getWorkoutPlan = readTool({
  name: 'get_workout_plan',
  description: 'One saved workout plan with its exercises, by id.',
  properties: { planId: { type: 'string' } },
  required: ['planId'],
  async execute(args, { userId }) {
    return { data: await workoutService.getPlan(userId, args.planId), evidence: [{ type: 'workout_plan', id: args.planId }] };
  },
});

// --------------------------------------------------- activity and vitals

const getActivitySummaryTool = readTool({
  name: 'get_activity_summary',
  description: 'Steps, exercise minutes, stand hours, calories burned and ring progress for today and the last N days (1-90, default 14).',
  properties: { days: { type: 'integer', minimum: 1, maximum: 90 } },
  async execute(args, { userId }) {
    return { data: await getActivitySummary(userId, args.days), evidence: [] };
  },
});

const getGlucoseSummaryTool = readTool({
  name: 'get_glucose_summary',
  description: 'Glucometer readings by day (average/min/max, time in range) compared with the latest lab fasting glucose, post-prandial glucose and HbA1c.',
  properties: { days: { type: 'integer', minimum: 1, maximum: 365 } },
  async execute(args, { userId }) {
    return { data: await getGlucoseSummary(userId, args.days), evidence: [] };
  },
});

const getVitalsSummary = readTool({
  name: 'get_vitals_summary',
  description: 'Latest readings from paired devices: blood pressure, heart rate, SpO2, temperature, weight and similar.',
  async execute(args, { userId }) {
    return { data: { summary: await deviceService.getVitalsSummary(userId) }, evidence: [] };
  },
});

const getVitalsHistory = readTool({
  name: 'get_vitals_history',
  description: 'History of one vital sign over the last N days. Use get_vitals_summary to see which reading types exist.',
  properties: { readingType: { type: 'string' }, days: { type: 'integer', minimum: 1, maximum: 365 } },
  required: ['readingType'],
  async execute(args, { userId }) {
    return { data: { readings: await deviceService.getVitalsHistory(userId, args.readingType, args.days) }, evidence: [] };
  },
});

const listDevices = readTool({
  name: 'list_devices',
  description: 'Health devices (BLE monitors, wearables) paired to this profile.',
  async execute(args, { userId }) {
    return { data: { devices: await deviceService.listPairedDevices(userId) }, evidence: [] };
  },
});

module.exports = [
  getDietSummary,
  listFoodEntries,
  getDietRecommendations,
  listDietSchedules,
  getDietSchedule,
  listWorkouts,
  getWorkoutSummary,
  getWorkoutAnalytics,
  getExerciseProgression,
  listExercises,
  listWorkoutPlans,
  getWorkoutPlan,
  getActivitySummaryTool,
  getGlucoseSummaryTool,
  getVitalsSummary,
  getVitalsHistory,
  listDevices,
];
