-- Multi-language support for AI-generated explanatory text (insight
-- explanations, report narrative summaries, chat responses, custom
-- dashboard card labels/descriptions, and medication knowledge for a
-- medicine outside the curated knowledge base) - see
-- server/src/services/languageService.js. Never affects the app's own UI
-- chrome, only text a model generates per-user going forward.
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_language TEXT NOT NULL DEFAULT 'en';

-- A custom_parameter_groups row (see migration 015) is shown directly to
-- the user (group_label, and now a short description of what the group of
-- tests is for), so it needs one row per (test name, language) rather than
-- a single global one. Existing rows predate this column and were always
-- produced in English, so they become the 'en' rows going forward - no
-- backfill needed, the default handles it.
ALTER TABLE custom_parameter_groups ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'en';
ALTER TABLE custom_parameter_groups ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE custom_parameter_groups DROP CONSTRAINT IF EXISTS custom_parameter_groups_test_name_key_key;
ALTER TABLE custom_parameter_groups
  ADD CONSTRAINT custom_parameter_groups_name_lang_key UNIQUE (test_name_key, language);

-- Mirrors medicationKnowledgeBase.js's shape (category/usage/
-- activeIngredient/commonSideEffects/warnings) but for a medication name
-- that matches none of that file's curated entries. Generated by Claude on
-- first lookup (medicationKnowledgeService.js) and cached here per (name,
-- language) so a given medication/language pair is only ever generated
-- once - same pattern as custom_parameter_groups above.
CREATE TABLE IF NOT EXISTS medication_knowledge_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name_key TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'en',
  category TEXT,
  usage TEXT,
  active_ingredient TEXT,
  common_side_effects TEXT[] NOT NULL DEFAULT '{}',
  warnings TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (name_key, language)
);

-- A report's narrative summary is cached and only regenerated when its
-- source data actually changes (source_data_version) - language must gate
-- that cache the same way, or a user who switches language keeps seeing a
-- summary generated in their old one until the report's data next changes.
ALTER TABLE report_summary_versions ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'en';
