const {
  KMSClient,
  GenerateDataKeyCommand,
  DecryptCommand,
  ReEncryptCommand,
  DescribeKeyCommand,
} = require('@aws-sdk/client-kms');

// Production key provider: the key-encryption key (KEK) never leaves AWS
// KMS. Each file's data key (DEK) is generated by KMS, returned once in
// plaintext for the encryption, and stored only in wrapped (KMS-encrypted)
// form. Credentials come from the EC2 instance role via the SDK's default
// chain - no access keys are configured anywhere.
//
// Every call binds an EncryptionContext ({ app, userId, objectKey }): KMS
// refuses to unwrap a DEK under any other context, so a wrapped key copied
// onto another user's/file's row is useless.
function createAwsKmsProvider({ keyId, region, client } = {}) {
  if (!keyId) throw new Error('KMS_KEY_ID is required for KEY_PROVIDER=aws-kms');
  const kms = client || new KMSClient({ region });

  function encryptionContext(ctx) {
    return { app: 'myhealthpal', userId: String(ctx.userId), objectKey: String(ctx.objectKey) };
  }

  return {
    name: 'aws-kms',

    async generateDataKey(ctx) {
      const out = await kms.send(
        new GenerateDataKeyCommand({ KeyId: keyId, KeySpec: 'AES_256', EncryptionContext: encryptionContext(ctx) })
      );
      return {
        plaintextKey: Buffer.from(out.Plaintext),
        wrappedKey: Buffer.from(out.CiphertextBlob),
        keyReference: out.KeyId, // full key ARN
        keyVersion: out.KeyId,
      };
    },

    async unwrapDataKey(wrappedKey, keyReference, ctx) {
      const out = await kms.send(
        new DecryptCommand({
          CiphertextBlob: wrappedKey,
          KeyId: keyReference || keyId,
          EncryptionContext: encryptionContext(ctx),
        })
      );
      return Buffer.from(out.Plaintext);
    },

    // KEK rotation: re-wrap an existing DEK under the current key without
    // ever exposing it to this process.
    async rewrapDataKey(wrappedKey, keyReference, ctx) {
      const context = encryptionContext(ctx);
      const out = await kms.send(
        new ReEncryptCommand({
          CiphertextBlob: wrappedKey,
          SourceKeyId: keyReference || keyId,
          SourceEncryptionContext: context,
          DestinationKeyId: keyId,
          DestinationEncryptionContext: context,
        })
      );
      return { wrappedKey: Buffer.from(out.CiphertextBlob), keyReference: out.KeyId, keyVersion: out.KeyId };
    },

    async currentKeyReference() {
      const out = await kms.send(new DescribeKeyCommand({ KeyId: keyId }));
      return out.KeyMetadata.Arn;
    },
  };
}

module.exports = { createAwsKmsProvider };
