// Curated, deterministic medication knowledge base - the medication-side
// analog of db/registry-seed-data.js. Every field here is a fixed clinical
// fact looked up by name match, never something an LLM is asked to judge at
// request time: matching a scanned/typed medication name to an entry (see
// findKnowledgeEntry) is the only "fuzzy" step, and it's a plain alias
// lookup like extraction/registry.js's findCanonicalMatches.
//
// `parameterLinks[].code` must be a code already present in
// db/registry-seed-data.js - medicationLinkingService looks it up through
// the same health_parameters registry the rest of the app uses, so a typo
// here just means the link silently doesn't attach rather than crashing.
//
// relationship: 'monitors_target' (the parameter this medication is meant
// to move) or 'monitors_side_effect' (a parameter to watch for unwanted
// drug effects). expected_direction is the direction of *that* expected
// effect - for a side-effect link it's the direction a problem would show
// up in, not a goal.
module.exports = [
  {
    id: 'metformin',
    genericNames: ['metformin', 'metformin hydrochloride'],
    brandNames: ['glucophage', 'glycomet', 'obimet', 'gluformin', 'fortamet'],
    category: 'Antidiabetic (biguanide)',
    usage:
      'Lowers blood glucose in type 2 diabetes by reducing glucose production in the liver and improving the body\'s response to insulin. Often the first medication tried for type 2 diabetes.',
    activeIngredient: 'Metformin hydrochloride',
    commonSideEffects: ['Nausea or upset stomach', 'Diarrhea', 'Metallic taste', 'Loss of appetite'],
    warnings: [
      'Rare but serious risk of lactic acidosis, especially with reduced kidney function',
      'Often paused before procedures using contrast dye - follow your provider\'s instructions',
      'Taking it with food reduces stomach upset',
    ],
    typicalDailyDose: { amountMin: 500, amountMax: 2550, unit: 'mg' },
    parameterLinks: [
      {
        code: 'glucose_fasting',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Fasting glucose typically begins improving within 1-2 weeks of consistent dosing.',
      },
      {
        code: 'glucose_post_prandial',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Post-meal glucose typically begins improving within 1-2 weeks of consistent dosing.',
      },
      {
        code: 'hba1c',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 8,
        onsetWeeksMax: 12,
        rationale: 'HbA1c reflects ~3 months of average glucose, so a meaningful change is usually only visible after 8-12 weeks.',
      },
    ],
  },
  {
    id: 'glimepiride',
    genericNames: ['glimepiride'],
    brandNames: ['amaryl', 'glimy', 'glimestar'],
    category: 'Antidiabetic (sulfonylurea)',
    usage: 'Stimulates the pancreas to release more insulin, lowering blood glucose in type 2 diabetes.',
    activeIngredient: 'Glimepiride',
    commonSideEffects: ['Low blood sugar (hypoglycemia)', 'Weight gain', 'Dizziness', 'Nausea'],
    warnings: [
      'Risk of hypoglycemia rises if a meal is skipped after dosing',
      'Alcohol can increase the risk of low blood sugar',
    ],
    typicalDailyDose: { amountMin: 1, amountMax: 8, unit: 'mg' },
    parameterLinks: [
      {
        code: 'glucose_fasting',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Fasting glucose typically begins improving within 1-2 weeks of consistent dosing.',
      },
      {
        code: 'hba1c',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 8,
        onsetWeeksMax: 12,
        rationale: 'HbA1c reflects ~3 months of average glucose, so a meaningful change is usually only visible after 8-12 weeks.',
      },
    ],
  },
  {
    id: 'sitagliptin',
    genericNames: ['sitagliptin'],
    brandNames: ['januvia', 'istavel', 'zita'],
    category: 'Antidiabetic (DPP-4 inhibitor)',
    usage: 'Helps the body release more of its own insulin after meals and lowers glucose production, used for type 2 diabetes.',
    activeIngredient: 'Sitagliptin',
    commonSideEffects: ['Upper respiratory infection symptoms', 'Headache', 'Stomach upset'],
    warnings: [
      'Rare reports of pancreatitis - seek care for severe abdominal pain',
      'Dose may need adjustment with reduced kidney function',
    ],
    typicalDailyDose: { amountMin: 25, amountMax: 100, unit: 'mg' },
    parameterLinks: [
      {
        code: 'hba1c',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 8,
        onsetWeeksMax: 12,
        rationale: 'HbA1c reflects ~3 months of average glucose, so a meaningful change is usually only visible after 8-12 weeks.',
      },
      {
        code: 'glucose_fasting',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 2,
        onsetWeeksMax: 4,
        rationale: 'Fasting glucose typically shows improvement within 2-4 weeks of consistent dosing.',
      },
    ],
  },
  {
    id: 'insulin',
    genericNames: ['insulin', 'insulin glargine', 'insulin aspart', 'insulin lispro', 'insulin isophane', 'insulin nph'],
    brandNames: ['lantus', 'humalog', 'novorapid', 'novolin', 'toujeo', 'basalog', 'huminsulin'],
    category: 'Antidiabetic (insulin)',
    usage: 'Replaces or supplements the body\'s own insulin to directly lower blood glucose, used in type 1 and advanced type 2 diabetes.',
    activeIngredient: 'Insulin (formulation varies by product - glargine, aspart, lispro, NPH, etc.)',
    commonSideEffects: ['Low blood sugar (hypoglycemia)', 'Injection site reactions', 'Weight gain'],
    warnings: [
      'Never share injection pens or needles',
      'Missed or doubled doses can cause dangerous blood sugar swings',
      'Storage temperature matters - follow the product label',
    ],
    typicalDailyDose: { amountMin: 10, amountMax: 100, unit: 'iu' },
    parameterLinks: [
      {
        code: 'glucose_fasting',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 0,
        onsetWeeksMax: 1,
        rationale: 'Insulin acts directly on blood glucose, so fasting glucose can respond within days.',
      },
      {
        code: 'glucose_post_prandial',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 0,
        onsetWeeksMax: 1,
        rationale: 'Insulin acts directly on blood glucose, so post-meal glucose can respond within days.',
      },
      {
        code: 'hba1c',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 8,
        onsetWeeksMax: 12,
        rationale: 'HbA1c reflects ~3 months of average glucose, so a meaningful change is usually only visible after 8-12 weeks.',
      },
    ],
  },
  {
    id: 'atorvastatin',
    genericNames: ['atorvastatin', 'atorvastatin calcium'],
    brandNames: ['lipitor', 'atorva', 'storvas'],
    category: 'Statin (cholesterol-lowering)',
    usage: 'Reduces LDL ("bad") cholesterol and triglycerides, and modestly raises HDL, to lower cardiovascular risk.',
    activeIngredient: 'Atorvastatin calcium',
    commonSideEffects: ['Muscle aches', 'Joint pain', 'Digestive upset', 'Headache'],
    warnings: [
      'Rare but serious risk of muscle breakdown (rhabdomyolysis) - report unexplained muscle pain or weakness',
      'Avoid grapefruit juice, which can raise drug levels',
      'Periodic liver enzyme monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 10, amountMax: 80, unit: 'mg' },
    parameterLinks: [
      {
        code: 'ldl_cholesterol',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'LDL cholesterol typically shows its main improvement 4-6 weeks after starting a stable dose.',
      },
      {
        code: 'total_cholesterol',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'Total cholesterol typically shows its main improvement 4-6 weeks after starting a stable dose.',
      },
      {
        code: 'triglycerides',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'Triglycerides typically shows its main improvement 4-6 weeks after starting a stable dose.',
      },
      {
        code: 'alt',
        relationship: 'monitors_side_effect',
        direction: 'stabilize',
        onsetWeeksMin: 4,
        onsetWeeksMax: 12,
        rationale: 'Statins can occasionally raise liver enzymes - ALT/AST are usually monitored a few weeks after starting or changing dose.',
      },
      {
        code: 'ast',
        relationship: 'monitors_side_effect',
        direction: 'stabilize',
        onsetWeeksMin: 4,
        onsetWeeksMax: 12,
        rationale: 'Statins can occasionally raise liver enzymes - ALT/AST are usually monitored a few weeks after starting or changing dose.',
      },
    ],
  },
  {
    id: 'rosuvastatin',
    genericNames: ['rosuvastatin', 'rosuvastatin calcium'],
    brandNames: ['crestor', 'rosuvas', 'rosufit'],
    category: 'Statin (cholesterol-lowering)',
    usage: 'Reduces LDL ("bad") cholesterol and triglycerides, and modestly raises HDL, to lower cardiovascular risk.',
    activeIngredient: 'Rosuvastatin calcium',
    commonSideEffects: ['Muscle aches', 'Headache', 'Digestive upset'],
    warnings: [
      'Rare but serious risk of muscle breakdown (rhabdomyolysis) - report unexplained muscle pain or weakness',
      'Periodic liver enzyme monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 5, amountMax: 40, unit: 'mg' },
    parameterLinks: [
      {
        code: 'ldl_cholesterol',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'LDL cholesterol typically shows its main improvement 4-6 weeks after starting a stable dose.',
      },
      {
        code: 'total_cholesterol',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'Total cholesterol typically shows its main improvement 4-6 weeks after starting a stable dose.',
      },
      {
        code: 'alt',
        relationship: 'monitors_side_effect',
        direction: 'stabilize',
        onsetWeeksMin: 4,
        onsetWeeksMax: 12,
        rationale: 'Statins can occasionally raise liver enzymes - ALT/AST are usually monitored a few weeks after starting or changing dose.',
      },
      {
        code: 'ast',
        relationship: 'monitors_side_effect',
        direction: 'stabilize',
        onsetWeeksMin: 4,
        onsetWeeksMax: 12,
        rationale: 'Statins can occasionally raise liver enzymes - ALT/AST are usually monitored a few weeks after starting or changing dose.',
      },
    ],
  },
  {
    id: 'fenofibrate',
    genericNames: ['fenofibrate'],
    brandNames: ['tricor', 'lipicard', 'fenolip'],
    category: 'Fibrate (cholesterol-lowering)',
    usage: 'Primarily lowers triglycerides and raises HDL cholesterol, used for high triglyceride levels.',
    activeIngredient: 'Fenofibrate',
    commonSideEffects: ['Digestive upset', 'Headache', 'Muscle pain'],
    warnings: [
      'Can increase statin-related muscle risk when combined with a statin',
      'Periodic liver and kidney function monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 48, amountMax: 145, unit: 'mg' },
    parameterLinks: [
      {
        code: 'triglycerides',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 4,
        onsetWeeksMax: 8,
        rationale: 'Triglycerides typically improve within 4-8 weeks of consistent dosing.',
      },
      {
        code: 'hdl_cholesterol',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 4,
        onsetWeeksMax: 8,
        rationale: 'HDL cholesterol typically shows a modest rise within 4-8 weeks of consistent dosing.',
      },
    ],
  },
  {
    id: 'levothyroxine',
    genericNames: ['levothyroxine', 'levothyroxine sodium'],
    brandNames: ['synthroid', 'eltroxin', 'thyronorm', 'euthyrox'],
    category: 'Thyroid hormone replacement',
    usage: 'Replaces thyroid hormone in hypothyroidism, used to bring TSH and T4/FT4 back into a normal range.',
    activeIngredient: 'Levothyroxine sodium',
    commonSideEffects: [
      'Usually minimal at a correctly matched dose',
      'Too-high a dose can cause palpitations, anxiety, insomnia, or weight loss',
    ],
    warnings: [
      'Take on an empty stomach, typically 30-60 minutes before breakfast, at a consistent time',
      'Calcium, iron supplements, and antacids can block absorption if taken too close together',
      'Never stop abruptly without medical guidance',
    ],
    typicalDailyDose: { amountMin: 25, amountMax: 200, unit: 'mcg' },
    parameterLinks: [
      {
        code: 'tsh',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 6,
        onsetWeeksMax: 8,
        rationale: 'TSH responds slowly - retesting is usually recommended no sooner than 6-8 weeks after starting or changing dose.',
      },
      {
        code: 'ft4',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'Free T4 typically normalizes faster than TSH, within about 4-6 weeks.',
      },
      {
        code: 't4',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 4,
        onsetWeeksMax: 6,
        rationale: 'Total T4 typically normalizes faster than TSH, within about 4-6 weeks.',
      },
    ],
  },
  {
    id: 'allopurinol',
    genericNames: ['allopurinol'],
    brandNames: ['zyloprim', 'zyloric'],
    category: 'Xanthine oxidase inhibitor (gout/high uric acid)',
    usage: 'Reduces the body\'s production of uric acid, used to prevent gout attacks and treat high uric acid levels.',
    activeIngredient: 'Allopurinol',
    commonSideEffects: ['Skin rash', 'Nausea', 'Diarrhea'],
    warnings: [
      'Rare but serious severe skin reactions (e.g. Stevens-Johnson syndrome) - stop and seek care for any rash',
      'Can trigger a gout flare when first started',
    ],
    typicalDailyDose: { amountMin: 100, amountMax: 800, unit: 'mg' },
    parameterLinks: [
      {
        code: 'uric_acid',
        relationship: 'monitors_target',
        direction: 'decrease',
        onsetWeeksMin: 2,
        onsetWeeksMax: 4,
        rationale: 'Uric acid typically starts dropping within 2-4 weeks of a stable dose.',
      },
    ],
  },
  {
    id: 'losartan',
    genericNames: ['losartan', 'losartan potassium'],
    brandNames: ['cozaar', 'losar', 'repace'],
    category: 'Antihypertensive (ARB)',
    usage: 'Relaxes blood vessels to lower blood pressure; also protects kidney function in diabetes. Blood pressure itself isn\'t tracked as a lab parameter here - keep monitoring it separately (cuff/monitor).',
    activeIngredient: 'Losartan potassium',
    commonSideEffects: ['Dizziness', 'Fatigue', 'Elevated potassium'],
    warnings: [
      'Not safe during pregnancy',
      'Avoid potassium supplements or salt substitutes unless advised',
      'Periodic kidney function and potassium monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 25, amountMax: 100, unit: 'mg' },
    parameterLinks: [
      {
        code: 'potassium',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'ARBs can raise potassium - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
      {
        code: 'creatinine',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'ARBs can transiently raise creatinine - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
      {
        code: 'egfr',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'ARBs can transiently lower eGFR - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
    ],
  },
  {
    id: 'enalapril',
    genericNames: ['enalapril', 'enalapril maleate'],
    brandNames: ['vasotec', 'envas', 'enam'],
    category: 'Antihypertensive (ACE inhibitor)',
    usage: 'Relaxes blood vessels to lower blood pressure; also protects kidney function in diabetes. Blood pressure itself isn\'t tracked as a lab parameter here - keep monitoring it separately (cuff/monitor).',
    activeIngredient: 'Enalapril maleate',
    commonSideEffects: ['Dry cough', 'Dizziness', 'Elevated potassium'],
    warnings: [
      'Not safe during pregnancy',
      'Rare but serious risk of angioedema (facial/throat swelling) - seek care immediately if it occurs',
      'Periodic kidney function and potassium monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 5, amountMax: 40, unit: 'mg' },
    parameterLinks: [
      {
        code: 'potassium',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'ACE inhibitors can raise potassium - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
      {
        code: 'creatinine',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'ACE inhibitors can transiently raise creatinine - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
    ],
  },
  {
    id: 'hydrochlorothiazide',
    genericNames: ['hydrochlorothiazide', 'hctz'],
    brandNames: ['microzide', 'aquazide'],
    category: 'Antihypertensive (thiazide diuretic)',
    usage: 'Helps the body eliminate excess salt and water to lower blood pressure. Blood pressure itself isn\'t tracked as a lab parameter here - keep monitoring it separately (cuff/monitor).',
    activeIngredient: 'Hydrochlorothiazide',
    commonSideEffects: ['Increased urination', 'Dizziness', 'Low potassium or sodium'],
    warnings: ['Can increase sun sensitivity', 'Periodic electrolyte monitoring is typical'],
    typicalDailyDose: { amountMin: 12.5, amountMax: 50, unit: 'mg' },
    parameterLinks: [
      {
        code: 'potassium',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'Thiazide diuretics can lower potassium - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
      {
        code: 'sodium',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'Thiazide diuretics can lower sodium - it\'s usually rechecked within the first few weeks of starting or increasing dose.',
      },
    ],
  },
  {
    id: 'furosemide',
    genericNames: ['furosemide'],
    brandNames: ['lasix', 'frusenex'],
    category: 'Diuretic (loop)',
    usage: 'A stronger "water pill" used for fluid overload (e.g. heart failure) that also lowers blood pressure somewhat.',
    activeIngredient: 'Furosemide',
    commonSideEffects: ['Increased urination', 'Dizziness', 'Low potassium, sodium, or magnesium'],
    warnings: [
      'Can cause dehydration or dangerously low blood pressure if overused',
      'Periodic electrolyte and kidney function monitoring is typical',
    ],
    typicalDailyDose: { amountMin: 20, amountMax: 80, unit: 'mg' },
    parameterLinks: [
      {
        code: 'potassium',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Loop diuretics can lower potassium quickly - it\'s usually rechecked within 1-2 weeks of starting or increasing dose.',
      },
      {
        code: 'sodium',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Loop diuretics can lower sodium quickly - it\'s usually rechecked within 1-2 weeks of starting or increasing dose.',
      },
      {
        code: 'creatinine',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 2,
        rationale: 'Loop diuretics can affect kidney function via volume changes - creatinine is usually rechecked within 1-2 weeks.',
      },
    ],
  },
  {
    id: 'ferrous_sulfate',
    genericNames: ['ferrous sulfate', 'ferrous fumarate', 'ferrous ascorbate', 'iron supplement'],
    brandNames: ['feosol', 'fefol', 'autrin'],
    category: 'Iron supplement',
    usage: 'Replenishes iron stores to treat or prevent iron-deficiency anemia.',
    activeIngredient: 'Elemental iron (as ferrous sulfate, fumarate, or ascorbate depending on the product)',
    commonSideEffects: ['Constipation', 'Dark or black stools (expected, not harmful)', 'Stomach upset'],
    warnings: [
      'Keep away from children - iron overdose is dangerous',
      'Vitamin C or citrus juice can improve absorption',
      'Can reduce absorption of some antibiotics or thyroid medication if taken together',
    ],
    typicalDailyDose: { amountMin: 65, amountMax: 325, unit: 'mg' },
    parameterLinks: [
      {
        code: 'iron',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 2,
        onsetWeeksMax: 4,
        rationale: 'Serum iron typically starts rising within 2-4 weeks of consistent dosing.',
      },
      {
        code: 'transferrin_saturation',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 2,
        onsetWeeksMax: 4,
        rationale: 'Transferrin saturation typically starts rising within 2-4 weeks of consistent dosing.',
      },
      {
        code: 'hemoglobin',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 6,
        onsetWeeksMax: 8,
        rationale: 'Hemoglobin takes longer to respond - a meaningful rise is usually only visible after 6-8 weeks.',
      },
    ],
  },
  {
    id: 'cholecalciferol',
    genericNames: ['cholecalciferol', 'vitamin d3', 'vitamin d'],
    brandNames: ['calcirol', 'd-rise', 'uprise-d3'],
    category: 'Vitamin D supplement',
    usage: 'Replenishes vitamin D stores, used for vitamin D deficiency and bone health support.',
    activeIngredient: 'Cholecalciferol (Vitamin D3)',
    commonSideEffects: ['Uncommon at typical doses', 'Very high doses can cause nausea or elevated calcium'],
    warnings: [
      'Very high, prolonged doses can raise blood calcium to unsafe levels',
      'Take with a meal containing some fat for best absorption',
    ],
    typicalDailyDose: { amountMin: 600, amountMax: 2000, unit: 'iu' },
    parameterLinks: [
      {
        code: 'vitamin_d',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 8,
        onsetWeeksMax: 12,
        rationale: 'Vitamin D stores build up slowly - a meaningful rise is usually only visible after 8-12 weeks.',
      },
    ],
  },
  {
    id: 'methylcobalamin',
    genericNames: ['methylcobalamin', 'cyanocobalamin', 'vitamin b12'],
    brandNames: ['methycobal', 'nurokind'],
    category: 'Vitamin B12 supplement',
    usage: 'Replenishes vitamin B12 stores, used for B12 deficiency, often alongside nerve-health support.',
    activeIngredient: 'Methylcobalamin or cyanocobalamin (Vitamin B12)',
    commonSideEffects: ['Generally well tolerated', 'Mild headache or nausea'],
    warnings: ['Injection forms may cause local site reactions', 'Very rare allergic reactions with injected cobalamin'],
    typicalDailyDose: { amountMin: 500, amountMax: 1500, unit: 'mcg' },
    parameterLinks: [
      {
        code: 'vitamin_b12',
        relationship: 'monitors_target',
        direction: 'increase',
        onsetWeeksMin: 4,
        onsetWeeksMax: 8,
        rationale: 'Vitamin B12 levels typically rise within 4-8 weeks of consistent dosing.',
      },
    ],
  },
  {
    id: 'omeprazole',
    genericNames: ['omeprazole', 'pantoprazole', 'esomeprazole', 'rabeprazole'],
    brandNames: ['prilosec', 'protonix', 'nexium', 'pantocid', 'omez'],
    category: 'Proton pump inhibitor (acid reflux)',
    usage: 'Reduces stomach acid production, used for acid reflux, gastritis, and ulcer healing.',
    activeIngredient: 'Omeprazole, pantoprazole, esomeprazole, or rabeprazole depending on the specific product',
    commonSideEffects: ['Headache', 'Stomach pain', 'Nausea', 'Diarrhea or constipation'],
    warnings: [
      'Long-term use is linked to lower B12, magnesium, and calcium absorption, and higher fracture risk',
      'Can reduce the effectiveness of some other drugs (e.g. clopidogrel) - check with a pharmacist',
    ],
    typicalDailyDose: { amountMin: 20, amountMax: 40, unit: 'mg' },
    parameterLinks: [
      {
        code: 'vitamin_b12',
        relationship: 'monitors_side_effect',
        direction: 'decrease',
        onsetWeeksMin: 24,
        onsetWeeksMax: 52,
        rationale: 'Long-term acid suppression can reduce B12 absorption over many months - occasional monitoring is reasonable with prolonged use.',
      },
    ],
  },
  {
    id: 'amlodipine',
    genericNames: ['amlodipine', 'amlodipine besylate'],
    brandNames: ['norvasc', 'amlopres', 'amlogard'],
    category: 'Antihypertensive (calcium channel blocker)',
    usage: 'Relaxes blood vessels to lower blood pressure. Blood pressure itself isn\'t tracked as a lab parameter here - keep monitoring it separately (cuff/monitor).',
    activeIngredient: 'Amlodipine besylate',
    commonSideEffects: ['Swelling in the ankles or feet', 'Flushing', 'Dizziness', 'Headache'],
    warnings: [
      'Ankle/foot swelling is dose-related and common - mention it rather than stopping on your own',
      'Grapefruit juice can raise drug levels',
    ],
    typicalDailyDose: { amountMin: 2.5, amountMax: 10, unit: 'mg' },
    parameterLinks: [],
  },
  {
    id: 'azithromycin',
    genericNames: ['azithromycin', 'amoxicillin', 'amoxicillin clavulanate', 'ciprofloxacin', 'doxycycline'],
    brandNames: ['zithromax', 'azithral', 'augmentin', 'ciplox'],
    category: 'Antibiotic',
    usage: 'A short course to treat a bacterial infection. Not typically taken long-term and has no routine lab-parameter monitoring.',
    activeIngredient: 'Azithromycin, amoxicillin, amoxicillin/clavulanate, ciprofloxacin, or doxycycline depending on the specific product',
    commonSideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
    warnings: [
      'Finish the full prescribed course even if feeling better, unless a doctor says otherwise',
      'Report any signs of a severe allergic reaction (rash, swelling, difficulty breathing) immediately',
    ],
    typicalDailyDose: null,
    parameterLinks: [],
  },
  {
    id: 'paracetamol',
    genericNames: ['paracetamol', 'acetaminophen', 'ibuprofen', 'diclofenac', 'naproxen'],
    brandNames: ['tylenol', 'crocin', 'dolo', 'advil', 'brufen'],
    category: 'Analgesic / pain reliever',
    usage: 'Relieves pain and/or fever. Occasional use needs no lab monitoring; frequent, high-dose, or prolonged use can affect the liver (paracetamol/acetaminophen) or kidneys (ibuprofen/diclofenac/naproxen).',
    activeIngredient: 'Paracetamol/acetaminophen, ibuprofen, diclofenac, or naproxen depending on the specific product',
    commonSideEffects: ['Generally well tolerated occasionally', 'NSAIDs (ibuprofen/diclofenac/naproxen) can cause stomach upset'],
    warnings: [
      'Do not exceed the labeled maximum daily dose - paracetamol overdose can cause serious liver damage',
      'NSAIDs carry a risk of stomach bleeding and kidney strain with frequent/prolonged use, especially combined with blood thinners',
    ],
    typicalDailyDose: { amountMin: 500, amountMax: 3000, unit: 'mg' },
    parameterLinks: [
      {
        code: 'alt',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'Frequent or high-dose use can affect liver enzymes - worth checking if this is being taken regularly rather than occasionally.',
      },
      {
        code: 'creatinine',
        relationship: 'monitors_side_effect',
        direction: 'increase',
        onsetWeeksMin: 1,
        onsetWeeksMax: 4,
        rationale: 'Frequent NSAID use can affect kidney function - worth checking if this is being taken regularly rather than occasionally.',
      },
    ],
  },
];
